spring:
  security:
    user:
      name: "sandip"
      password: "sandip"
  mvc:
    pathmatch:
      matching-strategy: "ANT_PATH_MATCHER"
management:
  endpoints:
    web:
      exposure:
        include: "*"